#!/usr/bin/env python3
"""
Interactive .env file setup.
Run once: python scripts/setup_env.py
"""
import os
import secrets
import sys

ENV_FILE = ".env"
EXAMPLE_FILE = ".env.example"


def prompt(label: str, default: str = "", secret: bool = False) -> str:
    display = f"[{default}]" if default and not secret else ""
    suffix = f" {display}: " if display else ": "
    try:
        value = input(f"  {label}{suffix}").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)
    return value if value else default


def main() -> None:
    print("\n=== CureForge Pipeline — Environment Setup ===\n")

    if os.path.exists(ENV_FILE):
        overwrite = prompt(f"{ENV_FILE} already exists. Overwrite? (y/N)", default="N")
        if overwrite.lower() != "y":
            print("Aborted.")
            return

    generated_key = secrets.token_hex(32)

    values: dict[str, str] = {}

    print("\n── Database ──────────────────────────────")
    values["DATABASE_URL"] = prompt(
        "DATABASE_URL",
        default="postgresql+asyncpg://cureforge:cureforge@localhost:5432/cureforge",
    )

    print("\n── Redis ─────────────────────────────────")
    values["REDIS_URL"] = prompt("REDIS_URL", default="redis://localhost:6379/0")

    print("\n── API Key ───────────────────────────────")
    print(f"  (auto-generated: {generated_key})")
    values["API_KEY"] = prompt("API_KEY", default=generated_key)

    print("\n── Claude / Anthropic ────────────────────")
    values["ANTHROPIC_API_KEY"] = prompt("ANTHROPIC_API_KEY (sk-ant-...)", secret=True)

    print("\n── Gmail OAuth ───────────────────────────")
    values["GOOGLE_CREDENTIALS_FILE"] = prompt(
        "GOOGLE_CREDENTIALS_FILE", default="config/google_credentials.json"
    )
    values["GOOGLE_TOKEN_FILE"] = prompt("GOOGLE_TOKEN_FILE", default="config/google_token.json")
    values["GMAIL_OAUTH_REDIRECT_URI"] = prompt(
        "GMAIL_OAUTH_REDIRECT_URI", default="http://localhost:8000/oauth/callback"
    )

    print("\n── GitHub ────────────────────────────────")
    values["GITHUB_TOKEN"] = prompt("GITHUB_TOKEN (ghp_...)", secret=True)
    values["GITHUB_ORG"] = prompt("GITHUB_ORG", default="cureforge-sandbox")

    print("\n── Logging ───────────────────────────────")
    values["LOG_LEVEL"] = prompt("LOG_LEVEL", default="INFO")

    lines = [
        "# Generated by scripts/setup_env.py — do not commit this file\n\n"
    ]
    for k, v in values.items():
        lines.append(f"{k}={v}\n")

    with open(ENV_FILE, "w") as f:
        f.writelines(lines)

    print(f"\n✓ Written to {ENV_FILE}")
    print("\nNext steps:")
    print("  1. Run Gmail OAuth:  python scripts/setup_gmail_oauth.py")
    print("  2. Set up Pub/Sub:   python scripts/setup_pubsub.py")
    print("  3. Start stack:      docker compose up --build\n")


if __name__ == "__main__":
    main()
